export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const GET_REVIEW_BY_PRODUCTID_REQUEST = 'GET_REVIEW_BY_PRODUCTID_REQUEST';
export const GET_REVIEW_BY_PRODUCTID_SUCCESS = 'GET_REVIEW_BY_PRODUCTID_SUCCESS';
export const GET_REVIEW_BY_PRODUCTID_FAILURE = 'GET_REVIEW_BY_PRODUCTID_FAILURE';