export const ADD_ITEM_TO_WISHLIST_REQUEST = 'ADD_ITEM_TO_WISHLIST_REQUEST'
export const ADD_ITEM_TO_WISHLIST_SUCCESS = 'ADD_ITEM_TO_WISHLIST_SUCCESS'
export const ADD_ITEM_TO_WISHLIST_FAILURE = 'ADD_ITEM_TO_WISHLIST_FAILURE'

export const REMOVE_ITEM_TO_WISHLIST_REQUEST = 'REMOVE_ITEM_TO_WISHLIST_REQUEST'
export const REMOVE_ITEM_TO_WISHLIST_SUCCESS = 'REMOVE_ITEM_TO_WISHLIST_SUCCESS'
export const REMOVE_ITEM_TO_WISHLIST_FAILURE = 'REMOVE_ITEM_TO_WISHLIST_FAILURE'

export const GET_ALL_WISHLIST_REQUEST = 'GET_ALL_WISHLIST_REQUEST'
export const GET_ALL_WISHLIST_SUCCESS = 'GET_ALL_WISHLIST_SUCCESS'
export const GET_ALL_WISHLIST_FAILURE = 'GET_ALL_WISHLIST_FAILURE'
