export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE';

export const UPDATE_PRODUCT_BY_ID_REQUEST = 'UPDATE_PRODUCT_BY_ID_REQUEST';
export const UPDATE_PRODUCT_BY_ID_SUCCESS = 'UPDATE_PRODUCT_BY_ID_SUCCESS';
export const UPDATE_PRODUCT_BY_ID_FAILURE = 'UPDATE_PRODUCT_BY_ID_FAILURE';

export const DELETE_PRODUCT_BY_ID_REQUEST = 'DELETE_PRODUCT_BY_ID_REQUEST';
export const DELETE_PRODUCT_BY_ID_SUCCESS = 'DELETE_PRODUCT_BY_ID_SUCCESS';
export const DELETE_PRODUCT_BY_ID_FAILURE = 'DELETE_PRODUCT_BY_ID_FAILURE';

export const DELETE_ALL_PRODUCTS_REQUEST = 'DELETE_ALL_PRODUCTS_REQUEST';
export const DELETE_ALL_PRODUCTS_SUCCESS = 'DELETE_ALL_PRODUCTS_SUCCESS';
export const DELETE_ALL_PRODUCTS_FAILURE = 'DELETE_ALL_PRODUCTS_FAILURE';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const GET_ALL_PRODUCT_BY_SHOP_ID_REQUEST = 'GET_ALL_PRODUCT_BY_SHOP_ID_REQUEST';
export const GET_ALL_PRODUCT_BY_SHOP_ID_SUCCESS = 'GET_ALL_PRODUCT_BY_SHOP_ID_SUCCESS';
export const GET_ALL_PRODUCT_BY_SHOP_ID_FAILURE = 'GET_ALL_PRODUCT_BY_SHOP_ID_FAILURE';
