export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';

export const GET_CATEGORY_BY_ID_REQUEST = 'GET_CATEGORY_BY_ID_REQUEST';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILURE = 'GET_CATEGORY_BY_ID_FAILURE';

export const UPDATE_CATEGORY_BY_ID_REQUEST = 'UPDATE_CATEGORY_BY_ID_REQUEST';
export const UPDATE_CATEGORY_BY_ID_SUCCESS = 'UPDATE_CATEGORY_BY_ID_SUCCESS';
export const UPDATE_CATEGORY_BY_ID_FAILURE = 'UPDATE_CATEGORY_BY_ID_FAILURE';

export const DELETE_CATEGORY_BY_ID_REQUEST = 'DELETE_CATEGORY_BY_ID_REQUEST';
export const DELETE_CATEGORY_BY_ID_SUCCESS = 'DELETE_CATEGORY_BY_ID_SUCCESS';
export const DELETE_CATEGORY_BY_ID_FAILURE = 'DELETE_CATEGORY_BY_ID_FAILURE';

export const DELETE_ALL_CATEGORIES_REQUEST = 'DELETE_ALL_CATEGORIES_REQUEST';
export const DELETE_ALL_CATEGORIES_SUCCESS = 'DELETE_ALL_CATEGORIES_SUCCESS';
export const DELETE_ALL_CATEGORIES_FAILURE = 'DELETE_ALL_CATEGORIES_FAILURE';

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE'